// <auto-generated />
using System;
using BookingServices.Entities.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingServices.Entities.Migrations;

[DbContext(typeof(BookingDbContext))]
[Migration("20240107121219_init")]
partial class init
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("BookingServices.Entities.Entities.Bookings", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<DateTime>("BookingDate")
                    .HasColumnType("datetime(6)");

                b.Property<int>("BookingStatusId")
                    .HasColumnType("int");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime(6)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("tinyint(1)");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime(6)");

                b.Property<int>("NumberOfPeople")
                    .HasColumnType("int");

                b.Property<Guid>("TableId")
                    .HasColumnType("char(36)");

                b.HasKey("Id");

                b.HasIndex("CreatedBy");

                b.HasIndex("TableId");

                b.ToTable("Bookings");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.Customers", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("DateOfBirth")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<int>("Gender")
                    .HasColumnType("int");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("tinyint(1)");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("Customers");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.Others.EntityHistories", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("ActionBy")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<DateTime>("ActionDate")
                    .HasColumnType("datetime(6)");

                b.Property<string>("EntityChangeData")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("EntityId")
                    .HasColumnType("longtext");

                b.Property<string>("EntityName")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("RequestId")
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("EntityHistories");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.Others.Stogares", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime(6)");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("Stogares");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.RestaurantFloors", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<int>("Capacity")
                    .HasColumnType("int");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime(6)");

                b.Property<string>("ExtensionData")
                    .HasColumnType("longtext");

                b.Property<int>("FloorNumber")
                    .HasColumnType("int");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("LayoutUrl")
                    .HasColumnType("longtext");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<Guid>("RestaurantId")
                    .HasColumnType("char(36)");

                b.HasKey("Id");

                b.HasIndex("RestaurantId");

                b.ToTable("RestaurantFloors");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.RestaurantImages", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<Guid>("RestaurantId")
                    .HasColumnType("char(36)");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.HasIndex("RestaurantId");

                b.ToTable("RestaurantImages");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.RestaurantInformation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<TimeOnly>("CloseTime")
                    .HasColumnType("time(6)");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Email")
                    .HasColumnType("longtext");

                b.Property<string>("ExtensionData")
                    .HasColumnType("longtext");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("tinyint(1)");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime(6)");

                b.Property<TimeOnly>("OpenTime")
                    .HasColumnType("time(6)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("longtext");

                b.Property<string>("RestaurantName")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Website")
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("RestaurantInformation");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.Restaurants", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<int>("Capacity")
                    .HasColumnType("int");

                b.Property<string>("CloseHours")
                    .HasColumnType("longtext");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Greetings")
                    .HasColumnType("longtext");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("Location")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("OpenHours")
                    .HasColumnType("longtext");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("longtext");

                b.Property<decimal?>("Rating")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("TotalFloors")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Restaurants");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.Tables", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<int>("Capacity")
                    .HasColumnType("int");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime(6)");

                b.Property<string>("ExtensionData")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("tinyint(1)");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime(6)");

                b.Property<Guid>("RestaurantFloorId")
                    .HasColumnType("char(36)");

                b.Property<string>("TableName")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<int>("TableType")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("RestaurantFloorId");

                b.ToTable("Tables");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.Users", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<Guid>("CreatedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime(6)");

                b.Property<Guid?>("CustomerId")
                    .HasColumnType("char(36)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("tinyint(1)");

                b.Property<Guid?>("ModifiedBy")
                    .HasColumnType("char(36)");

                b.Property<DateTime?>("ModifiedDate")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<int>("Role")
                    .HasColumnType("int");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("varchar(255)");

                b.HasKey("Id");

                b.HasIndex("CustomerId")
                    .IsUnique()
                    .HasFilter("[Role] = 4");

                b.HasIndex("Username")
                    .IsUnique();

                b.ToTable("Users");

                b.HasData(
                    new
                    {
                        Id = new Guid("0ac4a5b1-1b4e-457d-8198-8b7885115714"),
                        CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                        CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsDeleted = false,
                        Name = "Admin",
                        Password = "2hbDqy5ETiSMP3RWokGi3uXYDcjF88x+KGbOhpRkkBxYCikh0Qp+Qn/amWcxzVQG",
                        Role = 1,
                        Username = "admin"
                    },
                    new
                    {
                        Id = new Guid("3d2dabca-da93-4aba-af5d-37016e2f68b1"),
                        CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                        CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsDeleted = false,
                        Name = "Manager",
                        Password = "Qn3UVkUllvtHBUXE/YY7EGdfEM3woLT+dAm4VK5nfe/QtNC7Ss12/da/2cbemeMk",
                        Role = 2,
                        Username = "manager"
                    },
                    new
                    {
                        Id = new Guid("6b285584-7296-4206-abea-979d8d96f9c5"),
                        CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                        CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsDeleted = false,
                        Name = "Staff",
                        Password = "YMJE5Km2H9wuTHXneQis1Jl6/rV0PpurSBWVuCcvftctnFxeqFPc2cUOUOF+T1dB",
                        Role = 3,
                        Username = "staff"
                    },
                    new
                    {
                        Id = new Guid("aa2d65ea-c810-413e-b9a1-011c722f9ca9"),
                        CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                        CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        IsDeleted = false,
                        Name = "Customer",
                        Password = "Nhw+PUuMhfY1dSr9VsdxopL6337BjpVe1kCQrhRBiHMPCuhUzTdC7GVsrtxzMvs1",
                        Role = 4,
                        Username = "customer"
                    });
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.Bookings", b =>
            {
                b.HasOne("BookingServices.Entities.Entities.Users", "User")
                    .WithMany()
                    .HasForeignKey("CreatedBy")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("BookingServices.Entities.Entities.Tables", "Table")
                    .WithMany("Bookings")
                    .HasForeignKey("TableId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Table");

                b.Navigation("User");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.RestaurantFloors", b =>
            {
                b.HasOne("BookingServices.Entities.Entities.Restaurants", "Restaurant")
                    .WithMany("RestaurantFloors")
                    .HasForeignKey("RestaurantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Restaurant");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.RestaurantImages", b =>
            {
                b.HasOne("BookingServices.Entities.Entities.Restaurants", "Restaurants")
                    .WithMany("RestaurantImages")
                    .HasForeignKey("RestaurantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Restaurants");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.Tables", b =>
            {
                b.HasOne("BookingServices.Entities.Entities.RestaurantFloors", "RestaurantFloor")
                    .WithMany("Tables")
                    .HasForeignKey("RestaurantFloorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("RestaurantFloor");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.Users", b =>
            {
                b.HasOne("BookingServices.Entities.Entities.Customers", "Customer")
                    .WithOne("User")
                    .HasForeignKey("BookingServices.Entities.Entities.Users", "CustomerId");

                b.Navigation("Customer");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.Customers", b =>
            {
                b.Navigation("User")
                    .IsRequired();
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.RestaurantFloors", b =>
            {
                b.Navigation("Tables");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.Restaurants", b =>
            {
                b.Navigation("RestaurantFloors");

                b.Navigation("RestaurantImages");
            });

        modelBuilder.Entity("BookingServices.Entities.Entities.Tables", b =>
            {
                b.Navigation("Bookings");
            });
#pragma warning restore 612, 618
    }
}
